#!/usr/bin/python
# vim: ts=4 sw=4 smarttab expandtab

import os
import sys

# Make life easier on developers

MYPATH = os.path.abspath(__file__)
MYDIR = os.path.dirname(MYPATH)
DEVMODEMSG = '*** DEVELOPER MODE: setting PYTHONPATH and LD_LIBRARY_PATH'

if MYDIR.endswith('src') and \
   os.path.exists(os.path.join(MYDIR, '.libs')) and \
   os.path.exists(os.path.join(MYDIR, 'pybind')):
    MYLIBPATH = os.path.join(MYDIR, '.libs')
    if 'LD_LIBRARY_PATH' in os.environ:
        if MYLIBPATH not in os.environ['LD_LIBRARY_PATH']:
            os.environ['LD_LIBRARY_PATH'] += ':' + MYLIBPATH
            print >> sys.stderr, DEVMODEMSG
            os.execvp('python', ['python'] + sys.argv)
    else:
        os.environ['LD_LIBRARY_PATH'] = MYLIBPATH
        print >> sys.stderr, DEVMODEMSG
        os.execvp('python', ['python'] + sys.argv)
    sys.path.insert(0, os.path.join(MYDIR, 'pybind'))

from ceph_rest_api import api_setup, app

addr, port = api_setup()

def parse_args():
    parser = argparse.ArgumentParser(description="Ceph REST API webapp")
    parser.add_argument('-c', '--conf', help='Ceph configuration file')
    parser.add_argument('--cluster', help='Ceph cluster name')
    parser.add_argument('-n', '--name', help='Ceph client name')

    return parser.parse_args()

if __name__ == '__main__':

    import inspect

    parsed_args = parse_args()
    if parsed_args.conf:
        os.environ['CEPH_CONF'] = parsed_args.conf
    if parsed_args.cluster:
        os.environ['CEPH_CLUSTER_NAME'] = parsed_args.cluster
    if parsed_args.name:
        os.environ['CEPH_RESTAPI_CLIENT_NAME'] = parsed_args.name

    # import now, so env vars are available for configuration

    try:
        import ceph_rest_api
    except ImportError as e:
        print >> sys.stderr, "Error importing ceph_rest_api: ", str(e)
        sys.exit(1)

    # importing ceph_rest_api has set module globals 'app', 'addr', and 'port' 

    files = [os.path.split(fr[1])[-1] for fr in inspect.stack()]
    if 'pdb.py' in files:
        app.run(host=addr, port=port, debug=True, use_reloader=False, use_debugger=False)
    else:
        app.run(host=addr, port=port, debug=True)
